import { getTodoItem } from "@/modules/Data";
import Head from 'next/head'
import Link from "next/link";
import React, { useState, useEffect } from "react";
import { TodoDetails } from "@/components/TodoDetails";
import { useAuth } from "@clerk/nextjs";
import { UserButton } from "@clerk/clerk-react";
import { useRouter } from "next/router";

export default function Id(){
    const { isLoaded, userId, getToken } = useAuth();

    const [loading, setLoading] = useState(true);
    const [todoItem, setTodoItem] = useState(null);

    const router = useRouter();
    const {id} = router.query;
    

    useEffect(() => {
        async function process() {
            if (userId) {
                const authToken = await getToken({ template: "codehooks" });

                // fetch the item from backend and update the frontend useState
                const newTodoItem = await getTodoItem(authToken, id);
                setTodoItem(newTodoItem);
                setLoading(false);
            }
        }
        process();
    }, [isLoaded]);

    function refresh(updatedText){
        let updatedItem = todoItem;
        updatedItem.todoItem = updatedText;
        setTodoItem(updatedItem);
        
        const textAreaDom = document.getElementById('detailsContent');
        textAreaDom.innerHTML = "Updated To-do Item: " + todoItem.todoItem;
    }

    if(todoItem == null){
        return <span> Oops! </span>;
    } else {
        if (loading) {
            return (
                <>
                    <Head>
                        <title>Loading...</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <main className="loadingMain">
                        <h1 className="loadingTitle"> Loading... </h1>
                    </main>
                </>
            )
        } else {
            return (
                <>
                    <Head>
                        <title>To-do Item</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <main className="idMain">
                        <UserButton></UserButton>
                        <TodoDetails todoItem={ todoItem } refresh={ refresh }></TodoDetails>
                        <Link className="doneLinkId" href={ '/todo' }>See the List of Todo Items</Link>
                    </main>
                </>
            )
        }
    }
}