import { getTodoItem } from "@/modules/Data";
import Head from 'next/head'
import Link from "next/link";
import React, { useState, useEffect } from "react";
import { TodoDetails } from "@/components/TodoDetails";
import { useAuth } from "@clerk/nextjs";
import { UserButton } from "@clerk/clerk-react";
import { useRouter } from "next/router";

export default function Id(){
    const { isLoaded, userId, getToken } = useAuth();

    const [loading, setLoading] = useState(true);
    const [todoItem, setTodoItem] = useState(null);

    const router = useRouter();
    const {id} = router.query;
    

    useEffect(() => {
        async function process() {
            if (userId) {
                const authToken = await getToken({ template: "codehooks" });

                // fetch the item from backend and update the frontend useState
                const newTodoItem = await getTodoItem(authToken, id);
                setTodoItem(newTodoItem);
                setLoading(false);
            }
        }
        process();
    }, [isLoaded]);

    if(todoItem == null){
        return <span> Oops! </span>;
    } else {
        if (loading) {
            return <span> Loading... </span>;
        } else {
            return (
                <>
                    <Head>
                        <title>To-do Item with ID: { id }</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <main>
                        <UserButton></UserButton>
                        <h1>To-do Item with ID: { id }</h1>
                        <TodoDetails todoItem={ todoItem }></TodoDetails>
                        <Link href={ '/todo' }>See the List of Todo Items</Link>
                    </main>
                </>
            )
        }
    }
}