import Head from 'next/head'
import { SignIn, SignedOut, useAuth } from "@clerk/nextjs";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { userId } = useAuth();

  useEffect(() => {
    async function process() {
      if (userId) {
        router.push('/todo')
      }
    }
    process();
  }, [userId]);

  return (
    <>
      <Head>
        <title>Runqiu's To-do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Runqiu's To-do App</h1>
        <SignedOut>
          <SignIn redirectUrl="/todo"></SignIn>
        </SignedOut>
      </main>
    </>
  )
}
